import { createApp } from 'vue';
import App from './App.vue';
import router from '@/router';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import globalComponents from '@/plugins/global-components';
const app = createApp(App);
app.use(router);
app.mount('#app');
app.use(globalComponents);

import 'bootstrap/dist/js/bootstrap.js';
import funcPlugins from '@/plugins/func';
import person from '@/plugins/person';
import objPlugins from '@/plugins/obj';
app.use(funcPlugins);
app.use(objPlugins, { name: '오리' });
app.use(person);
// console.log('MODE:', import.meta.env.MODE);
// console.log('BASE_URL:', import.meta.env.BASE_URL);
// console.log('PROD:', import.meta.env.PROD);
// console.log('DEV:', import.meta.env.DEV);
// console.log('DEV:', import.meta.env.VITE_APP_API_URL);
